# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/rayan/cva6-custom-reg-instr/corev_apu/fpga/cva6_ooc.runs/synth_1/cva6.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
set_msg_config -id {Synth 8-4480} -limit 1000
set_msg_config  -id {[Synth 8-5858]}  -new_severity {INFO} 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/rayan/cva6-custom-reg-instr/corev_apu/fpga/cva6_ooc.cache/wt [current_project]
set_property parent.project_path /home/rayan/cva6-custom-reg-instr/corev_apu/fpga/cva6_ooc.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo-z7-20:part0:1.2 [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs {
  /home/rayan/cva6-custom-reg-instr/corev_apu/fpga/src/axi_sd_bridge/include
  /home/rayan/cva6-custom-reg-instr/vendor/pulp-platform/common_cells/include
  /home/rayan/cva6-custom-reg-instr/vendor/pulp-platform/axi/include
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/include
  /home/rayan/cva6-custom-reg-instr/corev_apu/register_interface/include
  /home/rayan/cva6-custom-reg-instr/core/include
} [current_fileset]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog {
  /home/rayan/cva6-custom-reg-instr/corev_apu/fpga/src/zybo-z7-20.svh
  /home/rayan/cva6-custom-reg-instr/vendor/pulp-platform/common_cells/include/common_cells/registers.svh
}
set_property file_type "Verilog Header" [get_files /home/rayan/cva6-custom-reg-instr/corev_apu/fpga/src/zybo-z7-20.svh]
set_property is_global_include true [get_files /home/rayan/cva6-custom-reg-instr/corev_apu/fpga/src/zybo-z7-20.svh]
set_property file_type "Verilog Header" [get_files /home/rayan/cva6-custom-reg-instr/vendor/pulp-platform/common_cells/include/common_cells/registers.svh]
set_property is_global_include true [get_files /home/rayan/cva6-custom-reg-instr/vendor/pulp-platform/common_cells/include/common_cells/registers.svh]
read_verilog -library xil_defaultlib -sv {
  /home/rayan/cva6-custom-reg-instr/vendor/pulp-platform/fpga-support/rtl/AsyncDpRam.sv
  /home/rayan/cva6-custom-reg-instr/vendor/pulp-platform/fpga-support/rtl/AsyncThreePortRam.sv
  /home/rayan/cva6-custom-reg-instr/vendor/pulp-platform/fpga-support/rtl/SyncDpRam.sv
  /home/rayan/cva6-custom-reg-instr/vendor/pulp-platform/fpga-support/rtl/SyncDpRam_ind_r_w.sv
  /home/rayan/cva6-custom-reg-instr/vendor/pulp-platform/fpga-support/rtl/SyncSpRamBeNx64.sv
  /home/rayan/cva6-custom-reg-instr/vendor/pulp-platform/fpga-support/rtl/SyncThreePortRam.sv
  /home/rayan/cva6-custom-reg-instr/core/include/config_pkg.sv
  /home/rayan/cva6-custom-reg-instr/core/include/cv32a6_im_contest_config_pkg.sv
  /home/rayan/cva6-custom-reg-instr/core/include/riscv_pkg.sv
  /home/rayan/cva6-custom-reg-instr/core/include/ariane_pkg.sv
  /home/rayan/cva6-custom-reg-instr/core/cvfpu/src/fpnew_pkg.sv
  /home/rayan/cva6-custom-reg-instr/vendor/pulp-platform/common_cells/src/cf_math_pkg.sv
  /home/rayan/cva6-custom-reg-instr/core/acc_dispatcher.sv
  /home/rayan/cva6-custom-reg-instr/core/alu.sv
  /home/rayan/cva6-custom-reg-instr/core/amo_buffer.sv
  /home/rayan/cva6-custom-reg-instr/vendor/pulp-platform/axi/src/axi_pkg.sv
  /home/rayan/cva6-custom-reg-instr/corev_apu/tb/ariane_axi_pkg.sv
  /home/rayan/cva6-custom-reg-instr/core/ariane_regfile_ff.sv
  /home/rayan/cva6-custom-reg-instr/core/ariane_regfile_fpga.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/axi_adapter.sv
  /home/rayan/cva6-custom-reg-instr/core/axi_shim.sv
  /home/rayan/cva6-custom-reg-instr/core/frontend/bht.sv
  /home/rayan/cva6-custom-reg-instr/core/branch_unit.sv
  /home/rayan/cva6-custom-reg-instr/core/frontend/btb.sv
  /home/rayan/cva6-custom-reg-instr/core/include/build_config_pkg.sv
  /home/rayan/cva6-custom-reg-instr/core/include/std_cache_pkg.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/cache_ctrl.sv
  /home/rayan/cva6-custom-reg-instr/core/commit_stage.sv
  /home/rayan/cva6-custom-reg-instr/core/compressed_decoder.sv
  /home/rayan/cva6-custom-reg-instr/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/defs_div_sqrt_mvp.sv
  /home/rayan/cva6-custom-reg-instr/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/control_mvp.sv
  /home/rayan/cva6-custom-reg-instr/core/controller.sv
  /home/rayan/cva6-custom-reg-instr/vendor/pulp-platform/common_cells/src/counter.sv
  /home/rayan/cva6-custom-reg-instr/core/csr_buffer.sv
  /home/rayan/cva6-custom-reg-instr/core/csr_regfile.sv
  /home/rayan/cva6-custom-reg-instr/core/include/wt_cache_pkg.sv
  /home/rayan/cva6-custom-reg-instr/core/cva6_accel_first_pass_decoder_stub.sv
  /home/rayan/cva6-custom-reg-instr/core/cva6_fifo_v3.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/hpdcache_pkg.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/cva6_hpdcache_if_adapter.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/cva6_hpdcache_subsystem.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/cva6_hpdcache_subsystem_axi_arbiter.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_pkg.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/cva6_hpdcache_wrapper.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/cva6_icache.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/cva6_icache_axi_wrapper.sv
  /home/rayan/cva6-custom-reg-instr/core/cva6_mmu/cva6_mmu.sv
  /home/rayan/cva6-custom-reg-instr/core/cva6_mmu/cva6_ptw.sv
  /home/rayan/cva6-custom-reg-instr/core/cva6_rvfi_probes.sv
  /home/rayan/cva6-custom-reg-instr/core/cva6_mmu/cva6_shared_tlb.sv
  /home/rayan/cva6-custom-reg-instr/core/cva6_mmu/cva6_tlb.sv
  /home/rayan/cva6-custom-reg-instr/core/cvxif_compressed_if_driver.sv
  /home/rayan/cva6-custom-reg-instr/core/cvxif_fu.sv
  /home/rayan/cva6-custom-reg-instr/core/cvxif_issue_register_commit_if_driver.sv
  /home/rayan/cva6-custom-reg-instr/core/decoder.sv
  /home/rayan/cva6-custom-reg-instr/vendor/pulp-platform/common_cells/src/delta_counter.sv
  /home/rayan/cva6-custom-reg-instr/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/div_sqrt_top_mvp.sv
  /home/rayan/cva6-custom-reg-instr/core/ex_stage.sv
  /home/rayan/cva6-custom-reg-instr/vendor/pulp-platform/common_cells/src/exp_backoff.sv
  /home/rayan/cva6-custom-reg-instr/core/cvfpu/src/fpnew_cast_multi.sv
  /home/rayan/cva6-custom-reg-instr/core/cvfpu/src/fpnew_classifier.sv
  /home/rayan/cva6-custom-reg-instr/core/cvfpu/src/fpnew_divsqrt_multi.sv
  /home/rayan/cva6-custom-reg-instr/core/cvfpu/src/fpnew_fma.sv
  /home/rayan/cva6-custom-reg-instr/core/cvfpu/src/fpnew_fma_multi.sv
  /home/rayan/cva6-custom-reg-instr/core/cvfpu/src/fpnew_noncomp.sv
  /home/rayan/cva6-custom-reg-instr/core/cvfpu/src/fpnew_opgroup_block.sv
  /home/rayan/cva6-custom-reg-instr/core/cvfpu/src/fpnew_opgroup_fmt_slice.sv
  /home/rayan/cva6-custom-reg-instr/core/cvfpu/src/fpnew_opgroup_multifmt_slice.sv
  /home/rayan/cva6-custom-reg-instr/core/cvfpu/src/fpnew_rounding.sv
  /home/rayan/cva6-custom-reg-instr/core/cvfpu/src/fpnew_top.sv
  /home/rayan/cva6-custom-reg-instr/core/fpu_wrap.sv
  /home/rayan/cva6-custom-reg-instr/core/frontend/frontend.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/hpdcache.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_1hot_to_binary.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/hpdcache_amo.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/hpdcache_cmo.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/hpdcache_core_arbiter.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/hpdcache_ctrl.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/hpdcache_ctrl_pe.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_data_downsize.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_data_resize.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_data_upsize.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_decoder.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_demux.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_fifo_reg.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/hpdcache_flush.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_fxarb.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_lfsr.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_req_read_arbiter.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_req_write_arbiter.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_resp_demux.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_to_axi_read.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_to_axi_write.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/hpdcache_memctrl.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/hpdcache_miss_handler.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/hpdcache_mshr.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_mux.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_prio_1hot_encoder.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_regbank_wbyteenable_1rw.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_regbank_wmask_1rw.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_rrarb.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/hpdcache_rtab.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/common/macros/behav/hpdcache_sram_1rw.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram_wbyteenable.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/common/macros/behav/hpdcache_sram_wbyteenable_1rw.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram_wmask.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/common/macros/behav/hpdcache_sram_wmask_1rw.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sync_buffer.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/hpdcache_uncached.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/hpdcache_victim_plru.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/hpdcache_victim_random.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/hpdcache_victim_sel.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/hpdcache_wbuf.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_arb.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_wrapper.sv
  /home/rayan/cva6-custom-reg-instr/core/id_stage.sv
  /home/rayan/cva6-custom-reg-instr/core/frontend/instr_queue.sv
  /home/rayan/cva6-custom-reg-instr/core/instr_realign.sv
  /home/rayan/cva6-custom-reg-instr/core/frontend/instr_scan.sv
  /home/rayan/cva6-custom-reg-instr/core/issue_read_operands.sv
  /home/rayan/cva6-custom-reg-instr/core/issue_stage.sv
  /home/rayan/cva6-custom-reg-instr/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/iteration_div_sqrt_mvp.sv
  /home/rayan/cva6-custom-reg-instr/vendor/pulp-platform/common_cells/src/lfsr.sv
  /home/rayan/cva6-custom-reg-instr/vendor/pulp-platform/common_cells/src/lfsr_8bit.sv
  /home/rayan/cva6-custom-reg-instr/core/load_store_unit.sv
  /home/rayan/cva6-custom-reg-instr/core/load_unit.sv
  /home/rayan/cva6-custom-reg-instr/core/lsu_bypass.sv
  /home/rayan/cva6-custom-reg-instr/vendor/pulp-platform/common_cells/src/lzc.sv
  /home/rayan/cva6-custom-reg-instr/core/macro_decoder.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/miss_handler.sv
  /home/rayan/cva6-custom-reg-instr/core/mult.sv
  /home/rayan/cva6-custom-reg-instr/core/multiplier.sv
  /home/rayan/cva6-custom-reg-instr/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/norm_div_sqrt_mvp.sv
  /home/rayan/cva6-custom-reg-instr/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/nrbd_nrsc_mvp.sv
  /home/rayan/cva6-custom-reg-instr/core/perf_counters.sv
  /home/rayan/cva6-custom-reg-instr/core/pmp/src/pmp.sv
  /home/rayan/cva6-custom-reg-instr/core/pmp/src/pmp_data_if.sv
  /home/rayan/cva6-custom-reg-instr/core/pmp/src/pmp_entry.sv
  /home/rayan/cva6-custom-reg-instr/vendor/pulp-platform/common_cells/src/popcount.sv
  /home/rayan/cva6-custom-reg-instr/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/preprocess_mvp.sv
  /home/rayan/cva6-custom-reg-instr/core/frontend/ras.sv
  /home/rayan/cva6-custom-reg-instr/core/register_allocation_table.sv
  /home/rayan/cva6-custom-reg-instr/vendor/pulp-platform/common_cells/src/rr_arb_tree.sv
  /home/rayan/cva6-custom-reg-instr/core/scoreboard.sv
  /home/rayan/cva6-custom-reg-instr/core/serdiv.sv
  /home/rayan/cva6-custom-reg-instr/vendor/pulp-platform/common_cells/src/shift_reg.sv
  /home/rayan/cva6-custom-reg-instr/common/local/util/sram.sv
  /home/rayan/cva6-custom-reg-instr/common/local/util/sram_cache.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/std_cache_subsystem.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/std_nbdcache.sv
  /home/rayan/cva6-custom-reg-instr/core/store_buffer.sv
  /home/rayan/cva6-custom-reg-instr/core/store_unit.sv
  /home/rayan/cva6-custom-reg-instr/vendor/pulp-platform/common_cells/src/stream_arbiter.sv
  /home/rayan/cva6-custom-reg-instr/vendor/pulp-platform/common_cells/src/stream_arbiter_flushable.sv
  /home/rayan/cva6-custom-reg-instr/vendor/pulp-platform/common_cells/src/stream_demux.sv
  /home/rayan/cva6-custom-reg-instr/vendor/pulp-platform/common_cells/src/stream_mux.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/tag_cmp.sv
  /home/rayan/cva6-custom-reg-instr/common/local/util/tc_sram_fpga_wrapper.sv
  /home/rayan/cva6-custom-reg-instr/common/local/util/tc_sram_wrapper_cache_techno.sv
  /home/rayan/cva6-custom-reg-instr/vendor/pulp-platform/common_cells/src/unread.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/wt_axi_adapter.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/wt_cache_subsystem.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/wt_dcache.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/wt_dcache_ctrl.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/wt_dcache_mem.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/wt_dcache_missunit.sv
  /home/rayan/cva6-custom-reg-instr/core/cache_subsystem/wt_dcache_wbuffer.sv
  /home/rayan/cva6-custom-reg-instr/core/zcmt_decoder.sv
  /home/rayan/cva6-custom-reg-instr/core/cva6.sv
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top cva6 -part xc7z020clg400-1 -global_retiming on -mode out_of_context
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cva6.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file cva6_utilization_synth.rpt -pb cva6_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
